### ISSUE TITLE
Error in train.py

### ISSUE THREAD

**Issue by rmovva** [davidaknowles/tf_net#1]
Hi,

Thank you for releasing your work! It's been a great resource to look to for guidance.

There was an error that arose when I ran the train.py script (for the TF ARID3A) that I wasn't sure how to fix. Do you have any ideas on what might be happening here?

```
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    train_func,test_func,pred_func,params=double_net.net(sequence_length, ge.shape[0] if (len(cell_types)>1) else 0, n_channels, filter_widths, pool_sizes, n_hidden_array, rotation=rotation, l2reg=l2reg, additional_channels=3 if (use_cons) else 2 )
  File "/scratch/users/rmovva/tf_net-dk/double_net.py", line 91, in net
    updates=utils.AdaMax( not_fixed_params, cost, alpha=learning_rate)
  File "/scratch/users/rmovva/tf_net-dk/utils.py", line 23, in AdaMax
    g = T.grad(objective, w, disconnected_inputs='warn')
  File "/share/sw/free/theano/0.8.2/theano/gradient.py", line 561, in grad
    grad_dict, wrt, cost_name)
  File "/share/sw/free/theano/0.8.2/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/share/sw/free/theano/0.8.2/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/share/sw/free/theano/0.8.2/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/share/sw/free/theano/0.8.2/theano/tensor/nnet/abstract_conv.py", line 828, in grad
    d_bottom = bottom.type.filter_variable(d_bottom)
  File "/share/sw/free/theano/0.8.2/theano/tensor/type.py", line 233, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(float64, 4D) (of Variable AbstractConv2d_gradInputs{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(30, 6, 1, 10)}.0) into Type TensorType(float32, 4D). You can try to manually convert AbstractConv2d_gradInputs{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(30, 6, 1, 10)}.0 into a TensorType(float32, 4D).
srun: error: sh-3-5: task 0: Exited with exit code 1
```
Thanks,
Rajiv

**Comment by davidaknowles** [comment]
Hmm... looks to me like theano is struggling with a mix of float32 and float64. On my system(s) theano is always configured to use float32 and will throw an error if any of the data sent to the GPU is float64. The setting is theano.config.floatX, so maybe we should check that first. What do you get if you do "import theano; print(theano.config.floatX" on your system?

**Comment by rmovva** [comment]
Looks like it's float64. Should I add `theano.config.floatX = 'float32'
` after the theano import?

**Comment by davidaknowles** [comment]
I think you have to do that before you import theano. The easiest way is to put e.g. 
```
[global]
floatX = float32
```
in a file called `.theanorc` in your home directory. You can also use environment vars, see http://deeplearning.net/software/theano/library/config.html.

**Comment by rmovva** [comment]
Alright, thanks, putting it in the .theanorc seems to have worked!

Unrelatedly: Do you have an idea about estimates for how much memory / time training a net for a single TF takes? That information would be helpful as I'm running on a compute cluster (Sherlock -- it seems you might've used this too, given the SLURM_ARRAY_TASK_ID variable) that requires a specification of the workload. Also, did you train on a GPU?

**Comment by davidaknowles** [comment]
Great. Yeah I used Sherlock - this architecture/batch size ran fine on the Sherlock K80s, run time was maybe 15hr or so? If you want to use a bigger net than the K80s allow you can always decrease the batch size.
