### ISSUE TITLE
HCT-116 DNase -- not loading chrX data properly?

### ISSUE THREAD

**Issue by rmovva** [davidaknowles/tf_net#2]
Hi,

One more issue arose when I was training for some of the TFs:
```
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    dgf_lookup[cell_type]=read_cuts.read_both_strands_corrected(cell_type)
  File "/scratch/users/rmovva/tf_net-dk/read_cuts.py", line 84, in read_both_strands_corrected
    (data,where,total)=read_npz(cell_type)
  File "/scratch/users/rmovva/tf_net-dk/read_cuts.py", line 56, in read_npz
    data[strand][chrom]=d["data%s_%s" % (strand,chrom)]
  File "/share/sw/free/py-numpy/1.10.4/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 228, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'data+_chrX is not a file in the archive'
```
This occurs when I'm loading the DNase cut data for the HCT-116 cell type (so, only when I'm trying to train for some TFs, CEBPB for example) -- no other cell types display this behavior (at least as far as I've noticed). This leads me to question the data rather than the code, but perhaps you have some insight as to what's going on here?

Thanks,
Rajiv

**Comment by rmovva** [comment]
Oops, never mind -- looks like the script to generate the npz representation of the HCT116 DNase data somehow terminated early, so there was no data for chrX. Sorry for the false alarm.

**Comment by davidaknowles** [comment]
No problem!
