### ISSUE TITLE
Is it possible to load weights to only generate predictions?

### ISSUE THREAD

**Issue by rmovva** [davidaknowles/tf_net#3]
I was wondering if I can load pre-trained weights for a certain TF to skip training and only do testing. Since all the fits are stored as npz, I'm assuming yes, I'm just not sure how to adapt your implementation to do so.

**Comment by davidaknowles** [comment]
Yeah this is pretty easy, just do e.g.
```
archive=np.load("myfit.npz")
for k in params:
    params[k].set_value( archive[k] )
```
after setting up the model with `double_net.net`, then just use `test_func` or `pred_func` rather than `train_func`. It would also be a good idea to store the network architecture in the `.npz` so you can load that too.

**Comment by rmovva** [comment]
Thanks, got this working.
